"""
stereo_depth_live.py
---------------------
Real-time stereo depth estimation from two synchronized cameras.
Loads precomputed rectification maps from stereo_maps.npz (generated by
stereo_camera_calibration.py), rectifies each frame pair, computes
disparity with StereoSGBM, and displays a color-coded depth map.

Before you run — set up your environment:
    If you haven't already, create and activate a virtual environment:

    # 1. Create the venv (only once, from the repo root):
    python -m venv venv

    # 2. Activate it (every time you open a new terminal):
    #    Windows:
    venv\Scripts\activate
    #    macOS / Linux:
    source venv/bin/activate

    # 3. Install dependencies (only once, after activating):
    pip install -r requirements.txt

    You should see (venv) at the start of your terminal prompt.
    If you don't, the venv is not active and the script will fail with
    "ModuleNotFoundError: No module named 'cv2'".

    You also need to run stereo calibration first (NB17 or
    scripts/calibration/stereo_camera_calibration.py) to produce
    assets/calibration/stereo_maps.npz before running this script.

Usage:
    python scripts/stereo/stereo_depth_live.py
    python scripts/stereo/stereo_depth_live.py --maps assets/calibration/stereo_maps.npz
    python scripts/stereo/stereo_depth_live.py --left 0 --right 1

Arguments:
    --maps         Path to the stereo_maps.npz file from stereo_camera_calibration.py.
                   If omitted, the script looks for
                   assets/calibration/stereo_maps.npz automatically.
                   The script cannot run without this file — run calibration first.
    --left         Camera index for the left camera (default: 0)
    --right        Camera index for the right camera (default: 1)
    --width        Requested capture width in pixels (default: 1280)
    --height       Requested capture height in pixels (default: 720)
    --num-disp     StereoSGBM numDisparities — must be a positive multiple of 16.
                   Higher = detects farther objects but slower. (default: 64)
    --block-size   StereoSGBM blockSize — must be an odd number >= 5.
                   Larger = smoother depth map but less sharp edges. (default: 5)

How it works, step by step:
    1. Loads precomputed remap tables and the Q matrix from stereo_maps.npz.
    2. Opens both cameras simultaneously and sets the requested resolution.
    3. Each frame:
       a. Reads one frame from each camera.
       b. Rectifies both frames with cv2.remap using the precomputed maps — after
          this, horizontal lines in the left image correspond to the same rows in
          the right image (epipolar alignment).
       c. Converts both rectified frames to grayscale and runs StereoSGBM to
          compute a disparity map (brighter = closer, darker = farther away).
       d. Normalizes the disparity and applies a HOT colormap for visualization.
    4. Displays the result in one of three modes (cycle with D):
       - left+depth: left rectified image beside the color depth map
       - rectified_pair: both rectified images side by side with epipolar lines
       - depth_only: full-screen color depth map
    5. Overlays FPS and current display mode name on the window.

Controls:
    Q / Esc   quit the live window
    D         cycle through display modes: left+depth → rectified_pair → depth_only

After running:
    No files are saved. To extract metric depth values from the disparity map,
    use cv2.reprojectImageTo3D(disparity, Q) where Q is loaded from stereo_maps.npz.
    Brighter (hotter) colors in the depth map correspond to closer distances.
"""

import cv2
import numpy as np
import os
import time
import argparse

DEFAULT_MAP_PATHS = [
    "assets/calibration/stereo_maps.npz",
    "../assets/calibration/stereo_maps.npz",
]


def parse_args():
    p = argparse.ArgumentParser(description="Real-time stereo depth estimation.")
    p.add_argument("--maps",       default=None, help="Path to stereo_maps.npz")
    p.add_argument("--left",       type=int, default=0, help="Left camera index")
    p.add_argument("--right",      type=int, default=1, help="Right camera index")
    p.add_argument("--width",      type=int, default=1280)
    p.add_argument("--height",     type=int, default=720)
    p.add_argument("--num-disp",   type=int, default=64,
                   help="numDisparities (multiple of 16)")
    p.add_argument("--block-size", type=int, default=5,
                   help="blockSize (odd number >= 5)")
    return p.parse_args()


def load_maps(maps_path):
    paths_to_try = ([maps_path] if maps_path else []) + DEFAULT_MAP_PATHS
    for path in paths_to_try:
        if path and os.path.exists(path):
            data = np.load(path)
            print(f"Stereo maps loaded: {path}")
            if "baseline_m" in data:
                print(f"  Baseline: {float(data['baseline_m'])*100:.1f} cm")
            if "rms_stereo" in data:
                print(f"  Stereo RMS at calibration: {float(data['rms_stereo']):.4f} px")
            return (data["map1_L"], data["map2_L"],
                    data["map1_R"], data["map2_R"],
                    data["Q"])
    print("WARNING: No stereo_maps.npz found. Run stereo_camera_calibration.py first.")
    print("         Using identity maps (no rectification).")
    return None


def make_stereo_matcher(num_disp, block_size):
    bs = block_size
    return cv2.StereoSGBM_create(
        minDisparity=0,
        numDisparities=num_disp,
        blockSize=bs,
        P1=8 * 1 * bs ** 2,
        P2=32 * 1 * bs ** 2,
        disp12MaxDiff=1,
        uniquenessRatio=15,
        speckleWindowSize=100,
        speckleRange=32,
        mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY)


DISPLAY_MODES = ["left+depth", "rectified_pair", "depth_only"]


def main():
    args = parse_args()
    maps = load_maps(args.maps)

    if maps is None:
        return  # No maps, can't proceed meaningfully

    map1_L, map2_L, map1_R, map2_R, Q = maps
    stereo = make_stereo_matcher(args.num_disp, args.block_size)

    print(f"Left cam   : {args.left}   Right cam: {args.right}")
    print(f"Capture    : {args.width}×{args.height}")
    print(f"numDisp    : {args.num_disp}   blockSize: {args.block_size}")
    print("Controls   : Q/Esc=quit  |  D=cycle display mode")

    cap_L = cv2.VideoCapture(args.left)
    cap_R = cv2.VideoCapture(args.right)
    for cap in (cap_L, cap_R):
        cap.set(cv2.CAP_PROP_FRAME_WIDTH,  args.width)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)

    display_mode = 0
    prev_time = time.time()

    while True:
        ret_L, raw_L = cap_L.read()
        ret_R, raw_R = cap_R.read()
        if not (ret_L and ret_R):
            print("Camera read failed. Check that both cameras are connected.")
            break

        # ── Rectify ───────────────────────────────────────────────────────────
        left_rect  = cv2.remap(raw_L, map1_L, map2_L, cv2.INTER_LINEAR)
        right_rect = cv2.remap(raw_R, map1_R, map2_R, cv2.INTER_LINEAR)

        # ── Disparity ─────────────────────────────────────────────────────────
        left_gray  = cv2.cvtColor(left_rect,  cv2.COLOR_BGR2GRAY)
        right_gray = cv2.cvtColor(right_rect, cv2.COLOR_BGR2GRAY)
        disparity  = stereo.compute(left_gray, right_gray).astype(np.float32) / 16.0
        # Set invalid (zero/negative disparity) to nan for cleaner vis
        disparity_vis = disparity.copy()
        disparity_vis[disparity_vis <= 0] = np.nan

        # ── Depth colormap ────────────────────────────────────────────────────
        disp_norm = cv2.normalize(
            np.nan_to_num(disparity_vis, nan=0), None, 0, 255,
            cv2.NORM_MINMAX, cv2.CV_8U)
        depth_color = cv2.applyColorMap(disp_norm, cv2.COLORMAP_HOT)

        # ── Display ───────────────────────────────────────────────────────────
        mode_name = DISPLAY_MODES[display_mode]
        h, w = left_rect.shape[:2]

        if mode_name == "left+depth":
            display = np.hstack([
                cv2.resize(left_rect,  (w // 2, h // 2)),
                cv2.resize(depth_color, (w // 2, h // 2))])
        elif mode_name == "rectified_pair":
            l_small = cv2.resize(left_rect,  (w // 2, h // 2))
            r_small = cv2.resize(right_rect, (w // 2, h // 2))
            # Draw epipolar lines to verify rectification
            for y in range(0, h // 2, 40):
                cv2.line(l_small, (0, y), (w // 2, y), (0, 200, 0), 1)
                cv2.line(r_small, (0, y), (w // 2, y), (0, 200, 0), 1)
            display = np.hstack([l_small, r_small])
        else:
            display = cv2.resize(depth_color, (w, h))

        now = time.time()
        fps = 1.0 / max(now - prev_time, 1e-6)
        prev_time = now

        cv2.putText(display, f"FPS:{fps:.1f}  [{mode_name}]  D=cycle",
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)

        cv2.imshow("Stereo Depth  [Q=quit | D=mode]", display)
        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), 27):
            break
        if key == ord("d"):
            display_mode = (display_mode + 1) % len(DISPLAY_MODES)
            print(f"Display mode: {DISPLAY_MODES[display_mode]}")

    cap_L.release()
    cap_R.release()
    cv2.destroyAllWindows()
    print("Done.")


if __name__ == "__main__":
    main()
